name: CI/CD - Build, Test, and Push Images

on:
  push:
    branches: [ "main" ]

jobs:
  # ------ JOB 1: INTEGRACIÓN CONTINUA (CI) ------
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and run containers
        run: docker compose up --build -d

      - name: Wait for services to start
        run: sleep 10

      - name: Run smoke test
        run: |
          echo "Pinging frontend..."
          curl -f http://localhost:8080
          echo "Pinging backend API..."
          curl -f http://localhost:5000/items
      
      - name: Stop containers
        if: always()
        run: docker compose down

  # ------ JOB 2: ENTREGA CONTINUA (CD) ------
  push-to-registry:
    # 'needs' asegura que este job solo se ejecute si 'build-and-test' fue exitoso.
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Este paso configura herramientas avanzadas de build de Docker.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Este paso inicia sesión en Docker Hub usando los secrets.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Este paso construye y empuja la imagen del backend a Docker Hub.
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-portfolio-backend:latest

      # Este paso construye y empuja la imagen del frontend a Docker Hub.
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-portfolio-frontend:latest